### ISSUE TITLE
Remove pop-up console after selecting OS

### ISSUE THREAD

**Issue by zoutiyx** [gustawho/grub2-theme-breeze#1]
After selecting my linux OS from the list, a console screen pops up for a second with an ugly stretched font. How do I remove this?

**Comment by way2key** [comment]
Hey, I've got Ubuntu 18.x and the same problem.
I tried to lookup [in this tutorial](http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial)
If you solved the problem since that time or found any other solution. I would appreciate :)

**Comment by gustawho** [comment]
Hello, and sorry for the long delayed answer. If you're referring to this console screen, that's intended so you can nicely type your password (if set) or edit the boot options without "leaving" GRUB.
![screenshot_20180913_172925](https://user-images.githubusercontent.com/2186602/45519420-96e0ad00-b77a-11e8-8ad0-eee7b14bb2a8.png)
