### ISSUE TITLE
The theme doesn't load with 'background.jpg'.

### ISSUE THREAD

**Issue by fernandodemorais-jf** [gustawho/grub2-theme-breeze#12]
Hello,

The theme in `5.20.0` version fails to load with the background image in `.jpg` format.
I've managed to solve the problem just exporting the same background image in `.png`, and change the extension in `theme.txt` file:
```
desktop-image: "background.png"
```
Thanks!

**Comment by kajzersoze** [comment]
Yeah I can confirm this, it was giving me 'Invalid option" on boot.
It's fine with png

**Comment by gustawho** [comment]
Thanks for reporting this!
